---
#
# A few notes when updating the compilers:
#
# Need to change the path variable in the "stat" steps, in order for the
# unarchive step to work.
#
# This is done to avoid repeating the same unarchive step every time the entire
# playbook is run, but the compiler hasn't been changed.
#

- stat:
    path: "/usr/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz"
  register: linaro_aarch64_compiler
  tags:
    - compiler
    - install

- name: Get Linaro GCC aarch64 Linux GNU
  get_url:
    url: "https://releases.linaro.org/components/toolchain/binaries/5.3-2016.05/aarch64-linux-gnu/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz"
    dest: "/usr/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz"
    force: no
    checksum: md5:24ac2e26f50f49f3043f281440b41bba
  tags:
    - compiler
    - install

- name: Install Linaro GCC aarch64 Linux GNU
  unarchive:
    remote_src: yes
    src: "/usr/gcc-linaro-5.3.1-2016.05-x86_64_aarch64-linux-gnu.tar.xz"
    dest: "/usr/"
    extra_opts:
      - --strip-components=1
      - -J
    owner: root
    group: root
  when: linaro_aarch64_compiler.stat.exists == false
  tags:
    - compiler
    - install

- stat:
    path: "/usr/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf.tar.xz"
  register: linaro_arm_gnueabihf_compiler
  tags:
    - compiler
    - install

- name: Get Linaro GCC arm Linux gnueabihf
  get_url:
    url: "https://releases.linaro.org/components/toolchain/binaries/5.3-2016.05/arm-linux-gnueabihf/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf.tar.xz"
    dest: "/usr/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf.tar.xz"
    force: no
    checksum: md5:9815a2f56fea6f1ff14905ab5997326a
  tags:
    - compiler
    - install

- name: Install Linaro GCC arm Linux gnueabihf
  unarchive:
    remote_src: yes
    src: "/usr/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf.tar.xz"
    dest: "/usr/"
    extra_opts:
      - --strip-components=1
      - -J
    owner: root
    group: root
  when: linaro_arm_gnueabihf_compiler.stat.exists == false
  tags:
    - compiler
    - install

- stat:
    path: "/usr/gcc-6.3.0-mips-linux.tar.bz2"
  register: mips_compiler
  tags:
    - compiler
    - install
    - mips

- name: Get mips Linux GNU
  get_url:
    url: "https://storage.kernelci.org/images/toolchain/gcc-6.3.0-mips-linux.tar.bz2"
    force: no
    dest: "/usr/gcc-6.3.0-mips-linux.tar.bz2"
    checksum: md5:f8b05e98fce2dacc8479974d2d6c2b04
  tags:
    - compiler
    - install
    - mips

- name: Install mips Linux GNU
  unarchive:
    remote_src: yes
    src: "/usr/gcc-6.3.0-mips-linux.tar.bz2"
    dest: "/usr/"
    extra_opts:
      - --strip-components=1
      - -a
    owner: root
    group: root
  when: mips_compiler.stat.exists == false
  tags:
    - compiler
    - install
    - mips

- stat:
    path: "/usr/clang+llvm-5.0.0-linux-x86_64-ubuntu16.04.tar.xz"
  register: clang_x86_compiler
  tags:
    - compiler
    - install
    - clang

- name: Get clang for x86
  get_url:
    url: "http://releases.llvm.org/5.0.0/clang+llvm-5.0.0-linux-x86_64-ubuntu16.04.tar.xz"
    force: no
    dest: "/usr/clang+llvm-5.0.0-linux-x86_64-ubuntu16.04.tar.xz"
  tags:
    - compiler
    - install
    - clang
    
- name: Install clang for x86
  unarchive:
    remote_src: yes
    src: "/usr/clang+llvm-5.0.0-linux-x86_64-ubuntu16.04.tar.xz"
    dest: "/usr/"
    extra_opts:
      - -a
    owner: root
    group: root
  when: clang_x86_compiler.stat.exists == false
  tags:
    - compiler
    - install
    - clang


