---
- name: Copy the gitconfig file
  copy:
    src: "gitconfig"
    dest: "/etc/gitconfig"
    owner: root
    group: root
  tags:
    - gitconfig

- name: Create the mirrors directory
  file:
    path: "/srv/mirrors"
    state: directory
    owner: root
    group: root
  tags:
    - mirror

- name: Make a mirror of the Linux tree
  command: "git clone --mirror git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux.git"
  args:
    chdir: "/srv/mirrors"
    creates: "/srv/mirrors/linux.git"
  tags:
    - mirror

- name: Copy remote script
  copy:
    src: "add_remotes.sh"
    dest: "/srv/mirrors/add_remotes.sh"
    owner: root
    group: root
    mode: 755
  tags:
    - mirror
    - remotes

- name: Add remote URLs to the mirror
  command: "/srv/mirrors/add_remotes.sh"
  tags:
    - mirror
    - remotes

- name: Deploy the mirror update script
  copy:
    src: "update_mirror.sh"
    dest: "/srv/mirrors/update_mirror.sh"
    backup: yes
    owner: root
    group: root
    mode: 755
  tags:
    - mirror
    - cron
    - update

- name: Setup the mirror update cron job
  cron:
    name: "Update mirrors"
    cron_file: "update-mirrors"
    user: root
    state: present
    job: "/srv/mirrors/update_mirror.sh /srv/mirrors/linux.git"
    minute: "*/20"
  tags:
    - mirror
    - cron
