---
- name: Install packages for Debian Jessie
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "jessie"
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - openjdk-7-jre-headless
  tags:
    - install
    - packages

- name: Install packages for Ubuntu and Debian Stretch
  when: (ansible_distribution == "Debian" and ansible_distribution_version == "stretch/sid") or
        (ansible_distribution == "Ubuntu" and ansible_distribution_release == "xenial")
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - openjdk-8-jre-headless
  tags:
    - install
    - packages
