---
- name: Install packages for Debian Buster
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "buster"
  apt:
    pkg: ['openjdk-11-jre-headless']
    state: latest
    update_cache: yes
  tags:
    - install
    - packages

- name: Install packages for Ubuntu
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_release == "xenial"
  apt:
    pkg: ['openjdk-8-jre-headless']
    state: latest
    update_cache: yes
  tags:
    - install
    - packages
